### ISSUE TITLE
Particles are not being garbage collected after Emitter.destroy()

### ISSUE THREAD

**Issue by NintendoBen** [pixijs/pixi-particles#22]
Calling particle.destroy nullifies particle.next causing the for loop to exit after destroying the first particle.

**Comment by andrewstart** [comment]
So it does. That was pretty dumb on my part.

**Comment by NintendoBen** [comment]
No worries - programming happens!

I noticed when I was debugging a box2d particle I created - the box2d bodies weren't being cleaned up.

There may also be a few other memory issues too - Even after I modified the for loop to continue, particles seem to be sticking around when I check the heap snapshot profiler in chrome.

**Comment by andrewstart** [comment]
When I get a chance to take care of this, I'll look around for other references.

**Comment by andrewstart** [comment]
I released version 1.6.3, which fixes the emitter issue and does other cleanup improvements. I didn't see any other references within the library that would cause particles to stick around, though.

**Comment by NintendoBen** [comment]
Awesome - I'll check it out tomorrow - Thanks Andrew!

**Comment by adoxographer** [comment]
Hi, 

I've been following this as well and have been trying to properly delete the particles but without success as well.

Having updated to 1.6.3 the problem still remains @andrewstart the issue is that it's being referenced by the renderer and never let go, unlike normal sprites

![particleleak](https://cloud.githubusercontent.com/assets/1608704/14116083/f9802e72-f5d5-11e5-92c0-2fb9823f8fbc.PNG)

I'm going to keep trying to figure it out but any help would be appreciated.

**Comment by andrewstart** [comment]
Ah, I see - the SpriteRenderer[ is resetting the batch size](https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/webgl/SpriteRenderer.js#L385) in order to [overwrite sprite batch entries](https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/webgl/SpriteRenderer.js#L278) which I assume has performance benefits from not trying to shrink and grow an array all the time. It also has the side effect of keeping references to destroyed sprites, if you have fewer sprites to draw than before. When you destroy a particle emitter, you suddenly have far fewer sprites than before. A workaround would be to reset the SpriteRenderer's sprites array when you want to wipe it, I believe with `myWebGLRenderer.plugins.sprite.sprites.length = 0`.

**Comment by adoxographer** [comment]
@andrewstart  unfortunately that doesn't seem to fix it, any ideas?

**Comment by andrewstart** [comment]
That was my only easy idea. I'll have to dig into it this weekend.

**Comment by andrewstart** [comment]
The other reference keeping the particles from getting garbage collected has been fixed in 1.6.6. You'll still need to reset the SpriteRenderer's `sprites` array, but once you do that the particles should get properly taken care of.

**Comment by adoxographer** [comment]
@andrewstart that worked, I can confirm they're being properly disposed now.

Thanks!

**Comment by bigbadwofl** [comment]
Upgraded to the latest pixi (4) and pixi particles (1.6.7) and particles are still not begin destroyed properly here.

Am I correct in assuming I can do:

`emitter.emit = false;`

and then a bit later

`emitter.destroy();`
`this.renderer.plugins.sprite.sprites.length = 0;`

When I step into the cleanup function, it doesn't find any particles to destroy (I wait until the particleCount == 0) eventhough I can still see a few faint dots on the screen.

**Comment by andrewstart** [comment]
That should be correct. `cleanup()` removes any active particles, which shouldn't find any particles if you've waited for all the particles to expire. `destroy()` is what wipes the particle pool. Are you using a Container or ParticleContainer?

**Comment by bigbadwofl** [comment]
Thanks for getting back to me! I'm using a Container but I found my issue. I was removing the emitter from an array right after destroying it. Moving the array.splice to right before the emitter.destroy resolved my problem.
